name: Build and test on all target OSs
on:
  push:
    branches: [master]
  # enable manual trigerring of the workflow
  workflow_dispatch: 
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: OS
        run: echo ${{ matrix.os }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: make build
        run: make build
      - name: make test
        run: make test
