name: Build and test on all target OSs
on:
  push:
    branches: [master]
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: build
        run: echo ${{ matrix.os }}
      - name: make build
        run: make build
      - name: make test
        run: make test
